"""
cpu_sap1.py
===========

A faithful model of the SAP-1 ("Simple As Possible 1") computer from
the textbooks and the BEN-EATER series, built entirely from the
hardware primitives in this project.

*Instructions* (single-byte; the high nibble is the opcode, the low
nibble is the memory operand):

+-----------------+------+----------------------------------------------+
| Binary opcode   | Hex  | Instruction             (operand is addressed  |
+=================+======+=====================+========================+
| 0000            | 0    | NOP : no operation                          |
| 0001            | 1    | LDA  : A <- MEM[operand]                    |
| 0010            | 2    | ADD  : A <- A + MEM[operand]                |
| 0011            | 3    | SUB  : A <- A - MEM[operand]                |
| 0100            | 4    | STA  : MEM[operand] <- A                    |
| 0101            | 5    | LDI  : A <- constant (the operand)          |
| 0110            | 6    | JMP  : PC <- operand                        |
| 0111            | 7    | JZ   : PC <- operand if ACC == 0             |
| 1000            | 8    | JC   : PC <- operand if CARRY == 1           |
| 1111            | F    | HLT  : halt the computer                   |
+-----------------+------+-----------------------------------------------+
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass
from typing import cast

from pytranscpu.arithmetic import ALU8Bits
from pytranscpu.decoder import Decoder4to16
from pytranscpu.gates import AndGate, OrGate
from pytranscpu.hardware import (
    HIGH,
    HIGH_IMPEDANCE,
    LOW,
    NMOS,
    Bit,
    Bus8,
    Byte,
    Component,
    bus8,
    int_to_bits,
)
from pytranscpu.latches import OneHotCounter6Bits, SRLatch
from pytranscpu.memory import ProgramCounter4Bits, Ram256Bits, Register8Bits


@dataclass(frozen=True, slots=True)
class ControlSignals:
    """Control signals generated by the Control Unit."""

    co: Bit
    mi: Bit
    ce: Bit
    ro: Bit
    ii: Bit
    io: Bit
    ai: Bit
    ao: Bit
    eo: Bit
    su: Bit
    bi: Bit
    fi: Bit
    j: Bit
    ri: Bit
    hlt: Bit


class ControlUnit(Component):
    """
    Control Unit for SAP-1 computer.

    Decodes the current micro-state (T-states from sequencer), the 4-bit
    opcode (from instruction register), and ALU flags to generate the
    control signals entirely using logic gates.
    """

    def __init__(self) -> None:
        self.decoder = Decoder4to16()

        # Memory instructions: LDA (1), ADD (2), SUB (3), STA (4)
        self.or_1_2 = OrGate()
        self.or_3_4 = OrGate()
        self.or_mem = OrGate()

        # T3 memory address loading (MI)
        self.and_t3_mem = AndGate()
        self.or_mi = OrGate()

        # RAM read operations: T4 with LDA (1), ADD (2), SUB (3)
        self.or_2_3 = OrGate()
        self.or_1_2_3 = OrGate()
        self.and_t4_read = AndGate()
        self.or_ro = OrGate()

        # RAM write: T4 with STA (4)
        self.and_ri = AndGate()

        # Accumulator out: T4 with STA (4)
        self.and_ao = AndGate()

        # B register in: T4 with ADD (2) or SUB (3)
        self.and_bi = AndGate()

        # Accumulator in:
        # T3 with LDI (5)
        # T4 with LDA (1)
        # T5 with ADD (2) or SUB (3)
        self.and_t3_ldi = AndGate()
        self.and_t4_lda = AndGate()
        self.and_t5_alu = AndGate()
        self.or_ai_sub = OrGate()
        self.or_ai = OrGate()

        # ALU sum out, subtract, flags in: T5 with ADD (2) or SUB (3)
        self.and_eo = AndGate()
        self.and_su = AndGate()
        self.and_fi = AndGate()

        # Jumps: JMP (6), JZ (7) & zero, JC (8) & carry
        self.and_jz = AndGate()
        self.and_jc = AndGate()
        self.or_jz_jc = OrGate()
        self.or_jump = OrGate()
        self.and_j = AndGate()

        # Instruction register out (IO):
        # T3 with memory instructions, LDI (5), or jumps
        self.or_io_target1 = OrGate()
        self.or_io_target2 = OrGate()
        self.and_io = AndGate()

        # Halt: T3 with HLT (15)
        self.and_hlt = AndGate()

    def __call__(
        self,
        t_states: tuple[Bit, ...],
        opcode: tuple[Bit, Bit, Bit, Bit],
        carry_flag: Bit,
        zero_flag: Bit,
    ) -> ControlSignals:
        t0 = t_states[0]
        t1 = t_states[1]
        t2 = t_states[2]
        t3 = t_states[3]
        t4 = t_states[4]
        t5 = t_states[5]

        i = self.decoder(opcode)

        # Memory instruction mask: LDA (1) | ADD (2) | SUB (3) | STA (4)
        is_mem = self.or_mem(self.or_1_2(i[1], i[2]), self.or_3_4(i[3], i[4]))

        # Jump conditions
        jz_active = self.and_jz(i[7], zero_flag)
        jc_active = self.and_jc(i[8], carry_flag)
        jump_active = self.or_jump(i[6], self.or_jz_jc(jz_active, jc_active))

        # Control signals
        co = t0
        mi = self.or_mi(t0, self.and_t3_mem(t3, is_mem))
        ce = t1

        ro_read = self.and_t4_read(t4, self.or_1_2_3(i[1], self.or_2_3(i[2], i[3])))
        ro = self.or_ro(t2, ro_read)

        ii = t2

        io_active = self.or_io_target2(
            is_mem,
            self.or_io_target1(i[5], jump_active),
        )
        io = self.and_io(t3, io_active)

        t3_ldi = self.and_t3_ldi(t3, i[5])
        t4_lda = self.and_t4_lda(t4, i[1])
        t5_alu = self.and_t5_alu(t5, self.or_2_3(i[2], i[3]))
        ai = self.or_ai(t3_ldi, self.or_ai_sub(t4_lda, t5_alu))

        ao = self.and_ao(t4, i[4])
        eo = self.and_eo(t5, self.or_2_3(i[2], i[3]))
        su = self.and_su(t5, i[3])
        bi = self.and_bi(t4, self.or_2_3(i[2], i[3]))
        fi = self.and_fi(t5, self.or_2_3(i[2], i[3]))
        j = self.and_j(t3, jump_active)
        ri = self.and_ri(t4, i[4])
        hlt = self.and_hlt(t3, i[15])

        return ControlSignals(
            co=co,
            mi=mi,
            ce=ce,
            ro=ro,
            ii=ii,
            io=io,
            ai=ai,
            ao=ao,
            eo=eo,
            su=su,
            bi=bi,
            fi=fi,
            j=j,
            ri=ri,
            hlt=hlt,
        )


class SAP1(Component):
    """
    A simple-as-possible computer.

    The public interface is:

        cpu = SAP1()
        cpu.clock_tick()      # advance the shared clock
        cpu.update()          # perform one micro-state transition
        ...

    ``halted``
        Becomes HIGH once a HLT instruction is read.

    ``out``
        The accumulator content, LSB first.
    """

    def __init__(self) -> None:
        self.program_counter = ProgramCounter4Bits()
        self.memory_address = Register8Bits()
        self.instruction_register = Register8Bits()
        self.accumulator = Register8Bits()
        self.b_register = Register8Bits()
        self.alu = ALU8Bits()
        self.decoder = Decoder4to16()
        self.ram = Ram256Bits()
        self.sequencer = OneHotCounter6Bits(initial_position=5)
        self.control_unit = ControlUnit()

        # Carry and zero flags, stored between micro-states.
        self.carry_flag = Register8Bits()
        self.zero_flag = Register8Bits()

        # Bus drivers: logic gates, decoders, NMOS transistors
        self.pc_bus_nmos = [NMOS() for _ in range(8)]
        self.ir_bus_nmos = [NMOS() for _ in range(8)]
        self.acc_bus_nmos = [NMOS() for _ in range(8)]
        self.ram_decoder = Decoder4to16()
        self.ram_load_and = [AndGate() for _ in range(16)]
        self.ram_bus_nmos = [[NMOS() for _ in range(8)] for _ in range(16)]

        # Clock control gates
        self.pc_or = OrGate()
        self.pc_and = AndGate()
        self.halt_latch = SRLatch()
        self.halt_and = AndGate()

        self.halted: bool = False
        self.clock_signal: Bit = LOW

    def clock_tick(self) -> Bit:
        """Toggle the shared clock and return the new value."""
        if self.halted:
            return self.clock_signal
        self.clock_signal = HIGH if self.clock_signal is LOW else LOW
        self._update(self.clock_signal)
        return self.clock_signal

    def update(self) -> None:
        """Update the internal circuit state with current clock."""
        self._update(self.clock_signal)

    def micro_step(self) -> None:
        """Advance the sequencer by one micro-state and execute it."""
        if self.halted:
            return
        if self.clock_signal == HIGH:
            self.clock_tick()
        self.clock_tick()
        self.clock_tick()

    def step_instruction(self) -> None:
        """Advance execution until the next instruction fetch starts or halted."""
        if self.halted:
            return
        self.micro_step()
        while not self.halted and self.sequencer.state[0] != HIGH:
            self.micro_step()

    def run(self, max_steps: int = 1000) -> None:
        """Run instructions until halted or max_steps reached."""
        steps = 0
        while not self.halted and steps < max_steps:
            self.step_instruction()
            steps += 1

    def load_program(self, program: Sequence[Byte | int]) -> None:
        """Load a sequence of 8-bit values into RAM starting at address 0."""
        for addr, value in enumerate(program):
            if addr >= 16:
                break
            byte_val = int_to_bits(value, 8) if isinstance(value, int) else value
            # DFlipFlopSave: when clock transitions LOW->HIGH with save=HIGH,
            # master latch receives data during LOW and slave latch updates during HIGH.
            self.ram.registers[addr](byte_val, LOW, HIGH, LOW)
            self.ram.registers[addr](byte_val, HIGH, HIGH, LOW)
            self.ram.registers[addr](byte_val, LOW, LOW, LOW)

    def _update(self, clock: Bit) -> None:
        """Propagate signals through combinational and sequential components."""
        t_states = self.sequencer.state
        ir_opcode = cast(
            tuple[Bit, Bit, Bit, Bit],
            self.instruction_register.state[4:8],
        )
        carry_val = self.carry_flag.state[0]
        zero_val = self.zero_flag.state[0]

        ctrl = self.control_unit(t_states, ir_opcode, carry_val, zero_val)

        # Bus drivers
        # 1. Program Counter bus
        pc_bus = cast(
            Bus8,
            tuple(
                self.pc_bus_nmos[i](
                    ctrl.co,
                    self.program_counter.state[i] if i < 4 else LOW,
                )
                for i in range(8)
            ),
        )

        # 2. RAM bus
        mar_addr = cast(
            tuple[Bit, Bit, Bit, Bit],
            self.memory_address.state[0:4],
        )
        ram_sel = self.ram_decoder(mar_addr)
        ram_drivers = [
            cast(
                Bus8,
                tuple(
                    self.ram_bus_nmos[k][i](
                        self.ram_load_and[k](ram_sel[k], ctrl.ro),
                        self.ram.registers[k].state[i],
                    )
                    for i in range(8)
                ),
            )
            for k in range(16)
        ]
        ram_bus = bus8(*ram_drivers)

        # 3. Instruction Register bus (operand on low 4 bits, zeros on high 4 bits)
        ir_bus = cast(
            Bus8,
            tuple(
                self.ir_bus_nmos[i](
                    ctrl.io,
                    self.instruction_register.state[i] if i < 4 else LOW,
                )
                for i in range(8)
            ),
        )

        # 4. Accumulator bus
        acc_bus = cast(
            Bus8,
            tuple(
                self.acc_bus_nmos[i](ctrl.ao, self.accumulator.state[i])
                for i in range(8)
            ),
        )

        # 5. ALU bus & flags
        alu_bus, carry_out, zero_out = self.alu(
            self.accumulator.state,
            self.b_register.state,
            subtract=ctrl.su,
            load=ctrl.eo,
        )

        # Resolve the 8-bit bus
        current_bus = bus8(pc_bus, ram_bus, ir_bus, acc_bus, alu_bus)
        bus_bits = cast(
            Byte,
            tuple(LOW if s is HIGH_IMPEDANCE else s for s in current_bus),
        )

        # Sequential clocking
        pc_clock_en = self.pc_or(ctrl.ce, ctrl.j)
        pc_clk = self.pc_and(pc_clock_en, clock)
        bus_low4 = cast(tuple[Bit, Bit, Bit, Bit], bus_bits[0:4])
        self.program_counter(
            bus_low4,
            clock=pc_clk,
            save=ctrl.j,
            load=LOW,
        )

        self.memory_address(bus_bits, clock=clock, save=ctrl.mi, load=LOW)
        self.ram(bus_bits, address=mar_addr, clock=clock, save=ctrl.ri, load=LOW)
        self.instruction_register(bus_bits, clock=clock, save=ctrl.ii, load=LOW)
        self.accumulator(bus_bits, clock=clock, save=ctrl.ai, load=LOW)
        self.b_register(bus_bits, clock=clock, save=ctrl.bi, load=LOW)

        self.carry_flag(
            (carry_out, LOW, LOW, LOW, LOW, LOW, LOW, LOW),
            clock=clock,
            save=ctrl.fi,
            load=LOW,
        )
        self.zero_flag(
            (zero_out, LOW, LOW, LOW, LOW, LOW, LOW, LOW),
            clock=clock,
            save=ctrl.fi,
            load=LOW,
        )

        halt_set = self.halt_and(ctrl.hlt, clock)
        self.halt_latch(set_signal=halt_set, reset_signal=LOW)
        if self.halt_latch.q == HIGH:
            self.halted = True

        self.sequencer(clock)

    @property
    def out(self) -> Byte:
        """The accumulator content, LSB first."""
        return self.accumulator.state
